Fix incompatibility issue with monaco-editor
Currently, we are getting the below error with the latest versions of monaco-editor and firebase:

```
typeError: Right-hand side of 'instanceof' is not callable
new t
node_modules/firepad/dist/firepad.min.js:1345
1342 | },
1343 | o = function () {
1344 | function t(t) {
```

I think this is the commit that's causing this issue: https://github.com/FirebaseExtended/firepad/commit/e39b4c147d6f41a246cb56232a0d6fc33833fd59